name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
      - name: Deploy to EC2
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@35.159.46.250 << 'EOF'
            cd /var/www/prop/prop
            git pull origin main
            npm install
            npm run build
            pm2 restart all
          EOF
